### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by robbiekruszynski** [wrightkhlebisol/consensys-final-dapp#1]
Hiya

Looking over your project I'm hoping I could see and have the ability to test 5 passing tests that work around your project. 
Thanks!

**Comment by wrightkhlebisol** [comment]
Hello @Robbiekruszynski

Unfortunately, I couldn't push my updated tests by the deadline, am I still allowed to push this?

Also, I checked the video afterwards and realised the quality was bad, but I didn't want to change anything so it wouldn't seem like I cheated, can I reupload that too?
